### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by TimNZ** [gcazaciuc/vscode-flow-ide#10]
Sorry for noob question.
What do I need to do for editor windows to not error on types?

![image](https://user-images.githubusercontent.com/1051701/33464666-556b2ab6-d6a8-11e7-9ca8-32345bb82c88.png)

**Comment by ablagodaryov** [comment]
Hello, @TimNZ set workspace preference with `"javascript.validate.enable": false`

**Comment by TimNZ** [comment]
@ablagodaryov Thanks, but that seems like the big hammer.

**Comment by AlexBlagodaryov** [comment]
@TimNZ No, you disable it only for current workspace, and flow will do all checks.
