### ISSUE TITLE
slow type check

### ISSUE THREAD

**Issue by ikzjfr0** [gcazaciuc/vscode-flow-ide#6]
I'm on Mac with 
1. vscode:  1.13.1
2. flowtype: 0.40.0:
3. Flow for Visual Studio Code: 0.7.0

Just realized the type check is so slow. I have to switch files to get updated

![refresh](https://user-images.githubusercontent.com/6456056/27426641-aea5dc6e-577f-11e7-9836-985688edfda5.gif)

Let me know if I need to provide more info

**Comment by gcazaciuc** [comment]
Are you sure you are using this extension(vscode-flow-ide) and not the oficial one(https://github.com/flowtype/flow-for-vscode ) :) ? 
I'm asking because this extension doesn't have a 0.7.0 version.

**Comment by gcazaciuc** [comment]
I'm closing it for now. Pls re-open if you believe it's a mistake.
